### ISSUE TITLE
Update Authentication Flow?

### ISSUE THREAD

**Issue by jabruder** [jetheis/MissingNPRPodcasts#10]
It looks like NPR changed the authentication flow to use OAUTH2. Is my understanding of the situation correct? If so, are you planning to update your app?

**Comment by jetheis** [comment]
Hi @jabruder! It's been a while since I've touched this project, and I honestly don't have a ton of free time right now, but when I get a chance (it could be a while), I'll update this app to support the latest auth API. I have received a few emails from other users saying they were having trouble authenticating, too, so that probably explains their problem.

In the meantime, if you or anyone else wants to make the updates yourself, I'll approve a PR and deploy a new version of the app to Heroku. Hopefully I'd be able to give you a quicker turnaround time on that.

Thanks!
Jimmy

**Comment by jprokos** [comment]
Hi, wish I had the knowledge to make the necessary changes. I tried today using a freshly generated key and it's not working.
